### ISSUE TITLE
pls help me to solve this:::

### ISSUE THREAD

**Issue by johnfelipe** [DenysMenfredy/skin-cancer-classification-project#1]
root@eh682214710:~/skin-cancer-classification-project# streamlit run app.py
	Traceback (most recent call last):
	  File "/usr/local/bin/streamlit", line 5, in <module>
		from streamlit.cli import main
	  File "/usr/local/lib/python3.8/dist-packages/streamlit/__init__.py", line 76, in <module>
		from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
	  File "/usr/local/lib/python3.8/dist-packages/streamlit/delta_generator.py", line 40, in <module>
		from streamlit.elements.altair import AltairMixin
	  File "/usr/local/lib/python3.8/dist-packages/streamlit/elements/altair.py", line 24, in <module>
		import altair as alt
	  File "/usr/local/lib/python3.8/dist-packages/altair/__init__.py", line 4, in <module>
		from .vegalite import *
	  File "/usr/local/lib/python3.8/dist-packages/altair/vegalite/__init__.py", line 2, in <module>
		from .v4 import *
	  File "/usr/local/lib/python3.8/dist-packages/altair/vegalite/v4/__init__.py", line 2, in <module>
		from .schema import *
	  File "/usr/local/lib/python3.8/dist-packages/altair/vegalite/v4/schema/__init__.py", line 2, in <module>
		from .core import *
	  File "/usr/local/lib/python3.8/dist-packages/altair/vegalite/v4/schema/core.py", line 4, in <module>
		from altair.utils.schemapi import SchemaBase, Undefined, _subclasses
	  File "/usr/local/lib/python3.8/dist-packages/altair/utils/__init__.py", line 1, in <module>
		from .core import (
	  File "/usr/local/lib/python3.8/dist-packages/altair/utils/core.py", line 14, in <module>
		import pandas as pd
	  File "/usr/local/lib/python3.8/dist-packages/pandas/__init__.py", line 22, in <module>
		from pandas.compat import (
	  File "/usr/local/lib/python3.8/dist-packages/pandas/compat/__init__.py", line 15, in <module>
		from pandas.compat.numpy import (
	  File "/usr/local/lib/python3.8/dist-packages/pandas/compat/numpy/__init__.py", line 20, in <module>
		raise ImportError(
	ImportError: this version of pandas is incompatible with numpy < 1.17.3
	your numpy version is 1.17.2.
	Please upgrade numpy to >= 1.17.3 to use this pandas version

**Comment by DenysMenfredy** [comment]
Which pandas version are you using? To fix this, you either need to upgrade your numpy version as the error suggests or downgrade your pandas version to a compatible one with your installed numpy...

**Comment by DenysMenfredy** [comment]
Are you still facing this problem? I'll close this issue if not.
